export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_Fail = 'CREATE_USER_Fail'
export const CREATE_USER_RESET = 'CREATE_USER_RESET'

export const LOGOUT_USER = "LOGOUT_USER";

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_Fail = 'LOGIN_USER_Fail'
export const LOGIN_USER_RESET = 'LOGIN_USER_RESET'